spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 7070

